New sidenav
appsignal/appsignal-docs pull request #344
Opened 2020-08-11 10:38 UTC by jonasbrinkhoff

- Updates the design of the sidenav.
- Works for most pages, but there's one issue that still needs to be fixed (described below).

@tombruijn & @jvanbaarsen: I wrote a ruby script (see `path_active` in `config.rb`) to set the active states of the navigation elements. It's pretty rudimentary, it basically just checks if the given path is part of the current path.  For example, on the ruby installation page (`/ruby/installation`), `/ruby/installation` and `/ruby/` are set active.

The only issue with that solution is that some sections have pages with different URLs. For instance, the AppSignal API section has pages with `/api/...` and `/push-api/...` urls, so the script wouldn't work for these pages.

I'd suggest to simply change the URLs of these pages, but I wanted to make sure first whether there's an argument that I don't see that speaks against this solution, or in case you have an idea for a better solution.

2020-08-12 11:41 UTC, tombruijn commented on source/_side_nav.html.erb
> +  sections = [
if we're going to define it like this, we should probably move it to a YAML file. Should be easier to edit.

2020-08-12 11:42 UTC, tombruijn commented on config.rb
> +    return current_page.url.include?(path)
```suggestion
    current_page.url.include?(path)
```
Unnecessary return

2020-08-12 11:44 UTC, tombruijn commented on source/_side_nav.html.erb
> +    <% sections.each do |section| %>
This whole thing seems really complex.

I don't like how I need to first click a section to wait for a page load and then only see the section links. That means it takes me X amount of clicks with page loads to go to the page I need to visit. Makes the navigation slower.

I'd rather keep the open and close logic in JavaScript.

2020-08-13 08:09 UTC, jonasbrinkhoff commented on source/_side_nav.html.erb
> +    <% sections.each do |section| %>
I talked with Wes about this (and I even implemented the old navigation style), but we came to the conclusion to keep it like it is now.

With the old navigation style, you either end up with a really long navigation (because multiple sub-navigations are open) or you'd loose the context of where you currently are (because once you opened another sub-navigation, the currently active one would close).

We are aware that the new solution increases the amount of clicks and time to navigate through the page, but we think that the drawbacks of the other solutions are bigger. In the long term, we'd like to move the documentation to Gatsby (or something similar) which would drastically reduce page load times and thereby hopefully eliminate the problems with the new navigation.

2020-08-13 08:09 UTC, jonasbrinkhoff commented on source/_side_nav.html.erb
> +  sections = [
Done :)

2020-08-13 08:15 UTC, tombruijn commented on source/_side_nav.html.erb
> +    <% sections.each do |section| %>
> With the old navigation style, you either end up with a really long navigation (because multiple sub-navigations are open) or you'd loose the context of where you currently are (because once you opened another sub-navigation, the currently active one would close).

There are other solutions to that problem as discussed. Another idea is to freely open sections while on a page, but then only the section you're in is open when you actually visit a page.

> In the long term, we'd like to move the documentation to Gatsby (or something similar) which would drastically reduce page load times and thereby hopefully eliminate the problems with the new navigation.

Load times are not the issue. As a user, on the deployed site, you're still waiting for page load times. That's my problem.

2020-08-13 09:36 UTC, jonasbrinkhoff commented
@wesoudshoorn 

> The links are now rendered directly inside an, which is unvalid HTML

I think something is missing here in this comment?

> We used to have a single side navigation and hid subitems with JS, we now have everything hidden based on Ruby

Updated the code, non-active sub-navigation elements are now rendered but hidden.

> Metrics and standalone agent links do not work

Fixed all links now

2020-08-13 09:37 UTC, jonasbrinkhoff commented
Updated all page names & links now, all links should now work properly in the navigation.

Also refactored the navigation a bit to make it more readable.

2020-08-13 09:53 UTC, wesoudshoorn commented
@jonasbrinkhoff https://deploy-preview-344--dreamy-wright-e9a95c.netlify.app/ the deploy preview is broken now?

2020-08-14 15:14 UTC, wesoudshoorn commented on data/navigation.yml
> +        name: "Standalone agent<sup>Beta</sup>"
```suggestion
        name: "Standalone agent <sup>Beta</sup>"
```

2020-08-19 08:31 UTC, jonasbrinkhoff commented on source/_side_nav.html.erb
> +    <% sections.each do |section| %>
> Another idea is to freely open sections while on a page, but then only the section you're in is open when you actually visit a page.

Really like this idea, implement it :)

2020-08-19 08:56 UTC, jonasbrinkhoff commented
Updated the behaviour of the side nav based on Toms suggestion and moved around some pages to make it work. Would be great if you could review it again :)

2020-08-19 09:26 UTC, jvanbaarsen approved these changes

2020-08-24 07:56 UTC, jvanbaarsen commented
@jonasbrinkhoff What is the status of this? Only waiting for reviews?

2020-08-24 07:58 UTC, jonasbrinkhoff commented
> @jonasbrinkhoff What is the status of this? Only waiting for reviews?

Yes, only waiting for reviews!

2020-08-24 09:04 UTC, tombruijn requested changes

2020-08-24 09:04 UTC, tombruijn commented on data/navigation.yml
> +                link: "/application/settings/notification-settings.html"
I wouldn't want to move pages in this PR. Yes it's now matching the new "navigation structure", but we're going to restructure it later in the docs improvement project. We then need to move it again.

The problem being that moving files require redirects to not break existing links. (This PR doesn't update those redirects as defined in `netlify.toml`.) So in this PR we would need to add more redirects, then later in the docs improvements projects we need to add even more redirects. And by then we've exhausted netlify's redirection list, if they still only support a limited amount of redirects.

2020-08-24 11:31 UTC, jonasbrinkhoff commented on config.rb
> +      return current_page.url === '/'
`current_page.url.include?("/")` would be true for all paths. That's why, if the given `path` is `"/"`, it should only return true if the `current_path` is also `"/"`.

2020-08-24 11:32 UTC, jonasbrinkhoff commented on config.rb
> +    current_page.url.include?(path)
Oh, good point! Didn't knew `start_with?` exists. I'll update it :)

2020-08-24 11:50 UTC, jonasbrinkhoff commented on data/navigation.yml
> +            link: "/application/overview.html"
I generally agree, but this would break the `path_active` function because of how `current_page.url` works.

Example:
- You rename `/application/overview.html` file to `/application/index.html`
- You then visit https://docs.appsignal.com/application/index.html
- You'd expect `current_page.url` to return `/application/index.html`, but in reality it returns just `/application/`
- And since `"/application/".start_with?("/application/index.html")` is `false`, `path_active` would return `false`

If you have any idea how to fix this, let me know.

2020-08-24 11:51 UTC, tombruijn commented on config.rb
> +      return current_page.url === '/'
Yes, but that would also be covered under `path == current_path.url`. That should then also work for most paths that we can match 1 to 1 and don't have to check for a partial match with `include?`/`start_with?`.

2020-08-24 12:08 UTC, jonasbrinkhoff commented on config.rb
> +      return current_page.url === '/'
I'm not sure if I got your comment. But we need a partial check, to determine the active state of parent elements.

Here's how `path_active` should work like, maybe this makes things more clear:
- when on `"/"`
  - `path_active("/")` should be `true`
  - `path_active("/application/")` should be `false`
- when on `"/application/"`
  - `path_active("/")` should be `false` <- weird case
  - `path_active("/application/")` should be `true`
  - `path_active("/application/index.html")` should be `true` <- weird case (only exists if we use index.html)
  - `path_active("/application/new-application.html")` should be `false`

2020-08-24 14:01 UTC, tombruijn commented
@jonasbrinkhoff I've renamed all the overview.html to index.html and updated the logic in the last commit. Can you let me know if it works good now?

2020-08-24 15:09 UTC, tombruijn commented
I'll have a look what pages should be renamed back to their originals. I don't think the pages under "Your application > Settings" should really go there. I've put them there to give some form of structure, but every page upon themself is a feature  we should put in a better structure in the future.

2020-08-24 15:46 UTC, tombruijn commented
@jonasbrinkhoff I've redirected and reverted some files, see last commit. I think it's fine to merge now.

2020-08-25 07:23 UTC, jonasbrinkhoff commented
> @jonasbrinkhoff I've redirected and reverted some files, see last commit. I think it's fine to merge now.

Amazing, thanks for your help!

2020-08-25 07:23 UTC, merged