add ignore actions docs for nodejs
appsignal/appsignal-docs pull request #351
Opened 2020-09-10 14:47 UTC by shairyar

This PR adds a new menu called 'Ignore actions' in the docs for nodejs.

2020-09-10 15:32 UTC, tombruijn requested changes

2020-09-10 15:32 UTC, tombruijn commented on source/shared/_ignore_actions.md
>  Ignoring actions or namespaces will **ignore all transaction data** from this action or namespace. No errors and performance issues will be reported. [Custom metrics data](/metrics/custom.html) recor
```suggestion
Ignoring actions or namespaces will **ignore all transaction/span data** from this action or namespace. No errors and performance issues will be reported. [Custom metrics data](/metrics/custom.html) recorded in an action will still be reported.
```

For JavaScript we don't have transactions so let's also mention "span"s.

2020-09-10 15:32 UTC, tombruijn commented on source/nodejs/configuration/ignore-actions.html.md.erb
> +```
Can you add an empty newline at the end of this file as discussed in Slack DM?

2020-09-11 07:18 UTC, tombruijn approved these changes

2020-09-11 14:35 UTC, xadamy approved these changes

2020-09-14 08:37 UTC, merged