update known issues
appsignal/appsignal-docs pull request #355
Opened 2020-09-15 09:13 UTC by shairyar

This PR updates the list of known issues with the following 2 issues

1. Puma phased restart is broken.
2. Compatibility issue found between AppSignal ruby gem and bugsnag.

2020-09-15 09:24 UTC, jeffkreeftmeijer commented on source/support/known-issues/puma-phased-restart.html.md
> +- Puma phased restart are broken.
```suggestion
- The AppSignal integration stops, but is not restarted when using Puma phased restarts.
```

2020-09-15 09:24 UTC, jeffkreeftmeijer commented on source/support/known-issues/bugsnag-compatibility.html.md
> +- AppSignal for Ruby gem versions: `v2.9.17` - `v2.11.0` (see [workarounds](#workaround))
```suggestion
- AppSignal for Ruby, in combination with Bugsnag 6.12.0 and later
```

2020-09-15 09:24 UTC, jeffkreeftmeijer commented on source/support/known-issues/bugsnag-compatibility.html.md
> +- It produces system stack errors when running rake tasks
```suggestion
- Running both AppSignal and Bugsnag 6.12.x or later produces SystemStackErrors when running rake tasks
```

2020-09-15 09:24 UTC, jeffkreeftmeijer commented on source/support/known-issues/bugsnag-compatibility.html.md
> +Downgrade the Bugsnag to `6.11.x`, which doesn't use `Module.prepend` yet, or removing it altogether.
```suggestion
Downgrade the Bugsnag library to `6.11.1`, which doesn't use `Module.prepend` yet, or remove it altogether.
```

2020-09-15 09:24 UTC, jeffkreeftmeijer commented on source/support/known-issues/puma-phased-restart.html.md
> +title: Puma phased restart
```suggestion
title: Puma phased restarts
```

2020-09-15 09:24 UTC, jeffkreeftmeijer commented on source/support/known-issues/puma-phased-restart.html.md
> +- AppSignal for Ruby gem versions: `v2.9.17` (see [workarounds](#workaround)).
```suggestion
- AppSignal for Ruby gem version `v2.9.17` and later (see [workarounds](#workaround)).
```

2020-09-15 11:31 UTC, tombruijn requested changes

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues.html.md
> +  - Symptom: It produces system stack errors when running rake tasks.
```suggestion
- [Compatibility issue with other instrumentation gems](known-issues/gem-instrumentation-compatibility.html)
  - Symptom: Apps produce "SystemStackErrors" when other instrumentation gems are loaded, such as http_logger, bugsnag, datadog and potentially others.
```

It's not just Rake, it's all the instrumentations we have and other gems have too.

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues.html.md
> +      - AppSignal for Ruby package versions: `v2.9.17` - `v2.11.0`
I think every version is affected as we never have instrumented it differently.
```suggestion
      - AppSignal for Ruby package versions: `0.0.x` - most recent
```

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues/bugsnag-compatibility.html.md
> +title: Bugsnag Compatibility
```suggestion
title: Compatibility issue with other instrumentation gems
```

The filename should also be updated to `gem-instrumentation-compatibility.html`. It's not bugsnag specific.

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues/bugsnag-compatibility.html.md
> +- AppSignal for Ruby, in combination with Bugsnag 6.12.0 and later
```suggestion
- AppSignal for Ruby, all versions, in combination with:
  - http_logger gem 0.6.0 and later
  - Bugsnag gem 6.12.0 and later
  - Datadog gem
```

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues/puma-phased-restart.html.md
> +Locking to `2.9.16` should fix that issue for now.
```suggestion
- Downgrade the AppSignal gem to `2.9.16` until the issue has been resolved.
- Do not use Puma's phased restart feature until the issue has been resolved.
```

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues/puma-phased-restart.html.md
> +See issue [#575](https://github.com/appsignal/appsignal-ruby/issues/575) on the appsignal-ruby repo for more details on the specific error.
```suggestion
See [appsignal-ruby issue #575](https://github.com/appsignal/appsignal-ruby/issues/575) for more details on the specific error.
```

More descriptive link label.

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues/puma-phased-restart.html.md
> +We've added a new plugin to add our [Puma magic dashboard](https://docs.appsignal.com/ruby/integrations/puma.html#minutely-probe) in version `2.9.17` of our gem, which broke phased restarts.
```suggestion
We've added a new plugin to add our [Puma magic dashboard](https://docs.appsignal.com/ruby/integrations/puma.html#minutely-probe) in version `2.9.17` of our gem, which breaks Puma phased restarts.
```

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues/bugsnag-compatibility.html.md
> +Downgrade the Bugsnag library to `6.11.1`, which doesn't use `Module.prepend` yet, or remove it altogether.
```suggestion
- Downgrade the Bugsnag library to `6.11.1`.
- Downgrade other gems that introduce the same problem in newer versions.
- Remove either of the gems until the issue has been resolved.
```

2020-09-15 11:31 UTC, tombruijn commented on source/support/known-issues/bugsnag-compatibility.html.md
> +Running both AppSignal and Bugsnag 6.12.x or later produces SystemStackErrors when running rake tasks.
```suggestion
Upon executing a rake task or performing a Net::HTTP request the app will raise a "stack level too deep (SystemStackError)" error. There may also be other scenarios this "SystemStackError" occurs, as it can potentially occur with every type of instrumentation set up by the AppSignal gem and other gems.

This error caused by the AppSignal gem and other gems with instrumentation having different methods of instrumentation that are incompatible. These different methods cause aliased methods, set up by instrumentation gems, to be continuously called until Ruby's stack has been exhausted.

We're looking into solutions for this issue in [appsignal-ruby issue #603](https://github.com/appsignal/appsignal-ruby/issues/603). This issue also contains more information about the cause of the issue and potential solutions. Please report issues with other gems if encountered in this issue.
```

2020-09-15 11:32 UTC, tombruijn commented on source/support/known-issues.html.md
> +      - AppSignal for Ruby package versions: `v2.9.17`
```suggestion
      - AppSignal for Ruby package versions: `v2.9.17` - most recent
```

2020-09-15 12:22 UTC, jeffkreeftmeijer requested changes

2020-09-15 12:22 UTC, jeffkreeftmeijer commented on source/support/known-issues/bugsnag-compatibility.html.md
> +This error caused by the AppSignal gem and other gems with instrumentation having different methods of instrumentation that are incompatible. These different methods cause aliased methods, set up by
```suggestion
This error is caused by the AppSignal gem and other gems with instrumentation having different methods of instrumentation that are incompatible. These different methods cause aliased methods, set up by instrumentation gems, to be continuously called until Ruby's stack has been exhausted.
```

2020-09-15 12:22 UTC, jeffkreeftmeijer commented on source/support/known-issues/bugsnag-compatibility.html.md
> +- Remove either of the gems until the issue has been resolved.
This item in the known issues list was set up as a separate issue for only the issue with Bugsnag (even though it's caused by the same issue as the problems we're seeing with NR) to keep it clear for customers. I'm fine with having one known-issues item for all items related to #603, but I'd really like this to be a list of versions to downgrade to for all libraries we come across in the future.

2020-09-15 12:22 UTC, jeffkreeftmeijer commented on source/support/known-issues/bugsnag-compatibility.html.md
> +- Downgrade the Bugsnag library to `6.11.1`.
```suggestion
- Downgrade the Bugsnag library to `6.11.1`.
- Downgrade the http_logger library to `0.5.1`.
```

2020-09-15 13:58 UTC, tombruijn approved these changes

2020-09-15 13:58 UTC, tombruijn commented on source/support/known-issues.html.md
> +- [Compatibility issue with other instrumentation gems](known-issues/gem-instrumentation-compatibility.html)
we should probably move these to the top. Most recent issues listed first.

2020-09-15 14:05 UTC, shairyar commented on source/support/known-issues.html.md
> +- [Compatibility issue with other instrumentation gems](known-issues/gem-instrumentation-compatibility.html)
Ah yes I agree, thanks for pointing this out.

2020-09-15 14:07 UTC, shairyar commented on source/support/known-issues.html.md
> +- [Compatibility issue with other instrumentation gems](known-issues/gem-instrumentation-compatibility.html)
I am thinking I will move the 2 newly added issues to the top

2020-09-16 07:13 UTC, tombruijn approved these changes

2020-09-16 09:20 UTC, thijsc approved these changes

2020-09-17 12:52 UTC, matsimitsu approved these changes
Awesome!

2020-09-18 06:57 UTC, jeffkreeftmeijer approved these changes

2020-09-18 06:57 UTC, merged