Tagging and sample data quide
appsignal/appsignal-docs pull request #394
Opened 2020-10-28 11:49 UTC by shairyar

Create a guide for tagging and sample data. Merge the language specific docs into one guide.

2020-10-28 12:46 UTC, tombruijn commented on source/application/tagging-sample-data.html.md
> +You can supply extra context on errors and performance issues using tags and sample data.
Should we expand the tagging topic to also mention tagging for metrics? A tagging system also exists for metrics.

2020-10-29 10:00 UTC, shairyar commented on source/application/tagging-sample-data.html.md
> +You can supply extra context on errors and performance issues using tags and sample data.
I agree and we have tag for exceptions too

2020-10-29 10:15 UTC, tombruijn commented on source/application/tagging-sample-data.html.md
> +You can supply extra context on errors and performance issues using tags and sample data.
Yes, tags for exceptions (e.g. set_error and send_error), are set on the sample data.

2020-10-29 11:40 UTC, shairyar commented on source/application/tagging-sample-data.html.md
> +You can supply extra context on errors and performance issues using tags and sample data.
I am thinking if this guide should have a structure like filter data as well, where we can have separate sub guide for tag, sample data and then tag for metrics

2020-10-29 13:25 UTC, tombruijn commented on source/application/tagging-sample-data.html.md
> +You can supply extra context on errors and performance issues using tags and sample data.
Yeah that could work. If it becomes too long, or you're having trouble guiding people through it, split it up.

2020-11-18 09:42 UTC, tombruijn requested changes

2020-11-18 09:42 UTC, tombruijn commented on source/guides/tagging-sample-data/sample-data.html.md
> +### `custom_data`
Let's add a separate page for the custom data feature and explain it in more detail.

The rest of the page, should maybe be linked to from the Elixir and Node.js installation guides. As next steps for non-Phoenix and non-Plug apps.

2020-11-18 09:42 UTC, tombruijn commented on source/application/integrations/webhooks.html.md
> +      <td>This includes user set metadata (see <a href="/guides/tagging-sample-data/">Tagging feature]</a>.</td>
```suggestion
      <td>This includes user set metadata (see <a href="/guides/tagging-sample-data/">Tagging feature</a>.</td>
```

2020-11-18 09:42 UTC, tombruijn commented on data/navigation.yml
> -              -
Let's set up redirects in the `netlify.toml` file for pages you move.

2020-11-18 09:47 UTC, tombruijn commented
The above was discussed in a call to give more context.

2021-01-06 09:27 UTC, shairyar commented on source/guides/tagging-sample-data/tagging-request.html.md
> +### Limitations
I have moved this at the bottom of the page.

2021-01-06 09:27 UTC, shairyar commented on source/guides/tagging-sample-data/tagging-request.html.md
> +
I have added the introduction

2021-01-07 06:12 UTC, shairyar commented on source/guides/tagging-sample-data/index.html.md
> +---
I have renamed` tagging-sample-data` directory to `custom-data` and updated its references throughout the docs.

2021-01-07 06:19 UTC, shairyar commented on source/application/tagging-sample-data.html.md
> +   system.
I have removed this limit.

2021-01-07 07:36 UTC, shairyar commented on source/application/tagging-sample-data.html.md
> +---
File has been named.

2021-01-07 07:36 UTC, shairyar commented on source/application/tagging-sample-data.html.md
> +This can help to add information that is not already part of the request, session or environment parameters.
I have added more description

2021-01-15 11:15 UTC, tombruijn approved these changes
I made some changes, I think it's good to merge for now.

2021-01-15 11:24 UTC, shairyar commented on source/guides/custom-data/sample-data.html.md
> +## Node.js
Yes thats exactly what I had in my mind as this PR is becoming too long.

2021-01-15 11:39 UTC, merged