Mention the order of Appsignal.Phoenix and Plug.Builder
appsignal/appsignal-docs pull request #454
Opened 2021-05-05 11:04 UTC by shairyar

`Plug.Builder` redefines the call/2 function we’ve overwritten with the use `Appsignal.Phoenix` call so we need to call`Plug.Builder` before `Appsignal.Phoenix` call.

2021-05-06 06:59 UTC, jeffkreeftmeijer requested changes

2021-05-06 06:59 UTC, jeffkreeftmeijer commented on source/elixir/installation/umbrella.html.md
> +to `use Appsignal.Phoenix` in your application’s endpoint file and add this after `Plug.Builder`. If you have
Most apps don’t include Plug.Builder here, so we might want to move this to a note after this paragraph:

> If you include `use Plug.Builder` or any other module that redefines the `call/2` function, make sure to place the `use Appsignal.Phoenix` line after that.

2021-05-06 07:08 UTC, shairyar commented on source/elixir/installation/umbrella.html.md
> +to `use Appsignal.Phoenix` in your application’s endpoint file and add this after `Plug.Builder`. If you have
Thanks for the tip, i will make the change.

2021-05-07 07:15 UTC, jeffkreeftmeijer approved these changes

2021-05-07 07:16 UTC, merged