Add GitHub to integration navigation
appsignal/appsignal-docs pull request #462
Opened 2021-05-19 12:01 UTC by shairyar

2021-05-27 11:51 UTC, matsimitsu requested changes
Nice!

2021-05-27 11:51 UTC, matsimitsu commented on source/application/integrations/github.html.md
> +<img src="/assets/images/screenshots/github/connfigure.png" style="max-width: 650px" alt="GitHub AppSignal integration">
configure is written with a typo (connfigure)

2021-05-27 11:51 UTC, matsimitsu commented on source/application/integrations/github.html.md
> +You will be redirected to GitHub, here you should select your account/organization where the application sourcecode exists.
```suggestion
You will be redirected to GitHub, here you should select your account/organization where the application source code exists.
```

2021-05-27 11:55 UTC, shairyar commented on source/application/integrations/github.html.md
> +<img src="/assets/images/screenshots/github/connfigure.png" style="max-width: 650px" alt="GitHub AppSignal integration">
Fixed

2021-05-28 12:37 UTC, matsimitsu approved these changes

2021-05-28 12:47 UTC, merged