Add GraphiQL explorer
appsignal/appsignal-docs pull request #473
Opened 2021-07-27 09:23 UTC by shairyar

This PR allows the customer to play around with AppSignal's GraphQL using the GraphiQL app

2021-09-03 08:46 UTC, shairyar commented
You can play around with it here: https://deploy-preview-473--dreamy-wright-e9a95c.netlify.app/api/graphql-explorer.html

2021-09-06 07:47 UTC, thijsc requested changes
Nice! I'd like a short page with an introduction to what this is.

2021-09-06 10:09 UTC, tombruijn requested changes

2021-09-06 10:09 UTC, tombruijn commented on source/api/graphql-explorer.html.md
> +  <div id="graphiql" style="height: 100vh;">Loading..</div>
```suggestion
<div class="c-form">
  <label for="token" class="c-form__label">Enter your personal API <a href="https://appsignal.com/users/edit" target="_blank">token</a> </label><br>
  <input type="text" id="token" name="token" class="c-form__input">
</div>
<div id="graphiql" style="height: 100vh;">Loading..</div>
```

remove the indentation so it's not accidentally considered a pre or code block in the future.

2021-09-06 10:09 UTC, tombruijn commented on source/api/index.html.md
> +If you are interested in exploring our GraphQL API, you can do that using AppSignal's <a href="graphql-explorer.html" target="_blank">GraphiQL</a> app.
We can also add this to the side bar navigation so it's easier to find?

2021-09-06 10:09 UTC, tombruijn commented on source/api/graphql-explorer.html.md
> +<link href="https://unpkg.com/graphiql/graphiql.min.css" rel="stylesheet" />
I would maybe prefer a bundled approach. Add a package to the package.json and load it from there rather than load it from a remote source always.

2021-09-06 12:02 UTC, matsimitsu approved these changes
Once Tom's comments are resolved, I'm +1

2021-12-21 09:32 UTC, shairyar commented on source/api/index.html.md
> +If you are interested in exploring our GraphQL API, you can do that using AppSignal's <a href="graphql-explorer.html" target="_blank">GraphiQL</a> app.
Added to the navigation

2021-12-21 09:32 UTC, shairyar commented on source/api/graphql-explorer.html.md
> +<link href="https://unpkg.com/graphiql/graphiql.min.css" rel="stylesheet" />
I will do this as part of another PR

2021-12-21 09:55 UTC, thijsc approved these changes
I'm ok with shipping this and cleaning up the packages later.

2021-12-21 10:59 UTC, merged