Select tags when creating triggers
appsignal/appsignal-docs pull request #481
Opened 2021-09-16 12:50 UTC by shairyar

Customers usually miss selecting tags when creating a trigger, this results in triggers not generating alerts. The docs have been updated to mention the selection of tags is important.

2021-09-16 12:56 UTC, matsimitsu commented on source/anomaly-detection/index.html.md
> +Some metrics requires tags to be selected as well. If a metric has tags AppSignal will let you know, for example in the following trigger `action_mailer_process` metric was selected and AppSignal sho
Still a bit confusing, I think. 

> If tags were added when sending a metric to AppSignal, all tag keys must match in order to generate an alert. 

E.g. if a metric was tagged with `:namespace => "web", :action => "Homepage"`, both the `namespace` and `action` tags must be present in the anomaly detection form.

2021-09-16 13:34 UTC, shairyar commented on source/anomaly-detection/index.html.md
> +Some metrics requires tags to be selected as well. If a metric has tags AppSignal will let you know, for example in the following trigger `action_mailer_process` metric was selected and AppSignal sho
Let's expand on that example you gave, suppose I am sending the following metric to AppSignal

```
Appsignal.set_gauge("my_metric_name", 100, : namespace => "web", :action => "web")

```

Then while creating a trigger I need to apply both tags (`namespace` and `web`)

2021-09-16 13:38 UTC, matsimitsu commented on source/anomaly-detection/index.html.md
> +Some metrics requires tags to be selected as well. If a metric has tags AppSignal will let you know, for example in the following trigger `action_mailer_process` metric was selected and AppSignal sho
yes

2021-09-16 13:56 UTC, shairyar commented on source/anomaly-detection/index.html.md
> +Some metrics requires tags to be selected as well. If a metric has tags AppSignal will let you know, for example in the following trigger `action_mailer_process` metric was selected and AppSignal sho
I have improved the example.

2021-09-17 12:01 UTC, matsimitsu requested changes

2021-09-17 12:01 UTC, matsimitsu commented on source/anomaly-detection/index.html.md
> +<img src="/assets/images/screenshots/trigger-with-tags.png">
Could you use the markdown version of this tag? `![Trigger with tags](/images/screenshots/trigger-with-tags.png)`

2021-09-20 10:17 UTC, shairyar commented on source/anomaly-detection/index.html.md
> +<img src="/assets/images/screenshots/trigger-with-tags.png">
Done

2021-09-23 07:45 UTC, matsimitsu approved these changes

2021-09-23 07:46 UTC, merged