FAQ Doc Improvements
appsignal/appsignal-docs pull request #633
Opened 2022-07-21 14:54 UTC by noccor

2022-07-22 11:33 UTC, tombruijn requested changes

2022-07-22 11:33 UTC, tombruijn commented on source/faq.html.md
> +- [Getting Started](#getting-started)
Okay, let me start by saying I'm not a fan of using title case in headings. For me it's actually more difficult to read. I don't know why we would want to use it here. Is there a good reason to adopt title case for _every heading_? What are the benefits?

2022-07-22 11:33 UTC, tombruijn commented on source/faq.html.md
> +If you're new to AppSignal or want to know more about configuring AppSignal features, please [read our guides →](/guides/)
Why use the arrow symbol here instead of normal punctuation? And if we really need to use it, make it so that screen readers don't have to read it aloud. I've heard it's annoying for screen reader users.

2022-07-22 12:31 UTC, mmaksimovic commented on source/faq.html.md
> +- [Getting Started](#getting-started)
There is a writing standard called the Chicago Manual of Style used by publishers. We use it for the blog, and enforce it everywhere so that the style is the same.

I never pushed that to the docs, because that wasn't my focus at the time, but when Connor approached me, I agreed with using the same style everywhere, and we agreed on the industry standard. True, you may not see this within every company, but at least we would have consistency. 

For example, Ana and I spend our time making sure that every blog post follows these, but we didn't have the time to do the same for the docs.

2022-07-22 12:32 UTC, noccor commented on source/faq.html.md
> +If you're new to AppSignal or want to know more about configuring AppSignal features, please [read our guides →](/guides/)
This is a good point (arrow key, screen readers) let me take this into consideration.

2022-07-22 12:39 UTC, noccor commented on source/faq.html.md
> +- [Getting Started](#getting-started)
It's not yet publicly announced, but it is in the public (AppSignal) domain that there are some formatting guidelines now for docs. This includes title case as @mmaksimovic mentioned: https://3.basecamp.com/4738529/buckets/28330015/google_documents/5147903785 - there are a lot of arguments around title case vs sentence case, both have pros and cons, but in this case it feels right to follow the example set by our blog. 

The guidelines are still being tweaked and modified but the core of what was needed in order to start applying consistency during re-writes is in there. 

A larger announcement will follow.

2022-07-25 09:16 UTC, tombruijn commented on source/faq.html.md
> +- [Getting Started](#getting-started)
Left my reply to this on Basecamp: https://3.basecamp.com/4738529/buckets/28330015/messages/5157091142#__recording_5161130850

2022-07-25 09:38 UTC, roytomeij commented on source/faq.html.md
> +If you're new to AppSignal or want to know more about configuring AppSignal features, please [read our guides →](/guides/)
What was your reasoning behind including the arrow @noccor?

2022-07-25 10:07 UTC, roytomeij approved these changes

2022-07-25 10:07 UTC, noccor commented on source/faq.html.md
> +If you're new to AppSignal or want to know more about configuring AppSignal features, please [read our guides →](/guides/)
A visual hint that "this link takes you to a different page not a section within the current documentation"

2022-07-25 10:13 UTC, roytomeij commented on source/faq.html.md
> +If you're new to AppSignal or want to know more about configuring AppSignal features, please [read our guides →](/guides/)
Got it. If we want to do that everywhere, we could probably add this automatically in an accessible way using CSS or JS. I'd say we leave it out for now and fix it with code later.

2022-07-25 10:21 UTC, noccor commented on source/faq.html.md
> +If you're new to AppSignal or want to know more about configuring AppSignal features, please [read our guides →](/guides/)
Yes @roytomeij  - I've spent the past hour navigating our docs via a screen reader, we should add this in CSS.

2022-07-25 12:09 UTC, noccor commented on source/faq.html.md
> +If you're new to AppSignal or want to know more about configuring AppSignal features, please [read our guides →](/guides/)
Arrows are now removed ➡️ 🗑️ until we have a CSS solution :)

2022-07-25 12:10 UTC, noccor commented on source/faq.html.md
> +- [Getting Started](#getting-started)
As per my response on basecamp, for now, I'd like to keep these case changes and review once we've got more examples of documentation re-written following this style guideline and an ability. The guide section is currently being revised. This will give us an idea of casing in varying content, and we can if possible ask for 3rd party feedback.

2022-08-02 09:00 UTC, merged