Add deprecation warning
appsignal/appsignal-docs pull request #639
Opened 2022-08-03 14:22 UTC by noccor

2022-08-03 14:27 UTC, noccor commented
@roytomeij - how do we format dates here?

@jvanbaarsen - is there anything we should advise them to bridge the intercom gap, or is it not worth it being such a small group of users?

2022-08-04 08:00 UTC, jvanbaarsen commented
@noccor I'd say it's not worth it.

2022-08-04 10:50 UTC, roytomeij requested changes

2022-08-04 10:50 UTC, roytomeij commented on source/application/integrations/intercom.html.md
> +!> ⚠️ On October 1st 2022, we will discontinue all support for our Intercom integration. From this date onwards, Intercom integrations will no longer work with AppSignal. If your application currentl
Once, it's "Intercom integration," and once, it's "Intercom Integration" (with a capital I).

2022-08-04 10:51 UTC, roytomeij commented
> @roytomeij - how do we format dates here?

"August 4, 2022": with a comma in between the day and the year.

2022-08-04 10:52 UTC, roytomeij commented on source/application/integrations/intercom.html.md
> +!> ⚠️ On October 1st 2022, we will discontinue all support for our Intercom integration. From this date onwards, Intercom integrations will no longer work with AppSignal. If your application currentl
```suggestion
!> ⚠️ On October 1st, 2022, we will discontinue all support for our Intercom integration. From this date onwards, Intercom integrations will no longer work with AppSignal. If your application currently uses the AppSignal Intercom Integration, we advise removing the configuration from your codebase before the feature is deprecated.
```

2022-08-09 12:35 UTC, merged