Add logging docs
appsignal/appsignal-docs pull request #754
Opened 2022-09-19 11:28 UTC by noccor

2022-09-19 13:45 UTC, mmaksimovic requested changes
I had to nitpick, sorry @noccor! :D

I don't think that we'll get spotted by product hunters because of this page. 🤞 our PR campaign goes smoothly.

2022-09-19 13:45 UTC, mmaksimovic commented on source/posts/application/logging.mdx
> +  ⚠️ AppSignal currently only supports SysLog for configuring your application's
```suggestion
  ⚠️ AppSignal currently only supports Syslog for configuring your application's
```
Is this proper spelling?

2022-09-19 13:45 UTC, mmaksimovic commented on source/posts/application/logging.mdx
> +##### Generating a new SysLog Config File
```suggestion
##### Generating a new Syslog Config File
```

2022-09-19 13:45 UTC, mmaksimovic commented on source/posts/application/logging.mdx
> +## Trouble Shooting
```suggestion
## Troubleshooting
```

2022-09-19 13:45 UTC, mmaksimovic commented on source/posts/application/logging.mdx
> +Any changes made (excluding name) will not be applied retrospectively, and therefor will only apply to new logs.
```suggestion
Any changes made (excluding name) will not be applied retrospectively, and therefore will only apply to new logs.
```

therefor sounds a bit too archaic

2022-09-19 13:47 UTC, tombruijn commented on config/navigationLinks.js
> +            link: "/application/logging.html",
This might as well be moved to the "features" section, no? Gives it a more prominent place and makes it easier to find for first time explorers in our docs.

You could even split some of this content up (it's a long page) into multiple pages.

2022-09-19 14:07 UTC, tombruijn commented on source/posts/application/logging.mdx
> +- If a key-value pair has a key with the value of `msg` or `message` the value of this key will be parsed as the log message.
```suggestion
- If a key-value pair has a key with the name of `msg` or `message` the value of this key will be parsed as the log message.
```

2022-09-19 14:08 UTC, tombruijn commented on source/posts/application/logging.mdx
> +- If a key-value pair has a key with the value of `msg` or `message` the value of this key will be parsed as the log message.
```suggestion
- If a key-value pair has a key with the name of `msg` or `message` the value of this key will be parsed as the log message.
```

2022-09-19 14:14 UTC, tombruijn commented on source/posts/application/logging.mdx
> +Once you've updated the relevant config file, your Logs should become visible to AppSignal. You'll be able to view and query your logs from the AppSignal application.
They don't need to restart or reload config anywhere?

2022-09-19 14:15 UTC, tombruijn commented on source/posts/application/logging.mdx
> +Use the `Severity ˬ` drop down to filter the severity of logs
That dropdown symbol renders a bit weird.
![image](https://user-images.githubusercontent.com/282402/191038711-a68eb96d-6eff-4e81-b6f2-431533d22f21.png)

2022-09-19 14:16 UTC, tombruijn commented on source/posts/application/logging.mdx
> +`ps -ef |grep iterm`
```suggestion
`ps -ef | grep iterm`
```

2022-09-19 14:16 UTC, tombruijn commented on source/posts/application/logging.mdx
> +1. $ ps -ef |grep syslog
```suggestion
1. $ ps -ef | grep syslog
```

2022-09-19 14:17 UTC, tombruijn commented on source/posts/application/logging.mdx
> +8. @@appsignal-endpoint.net:6514;AppsignalFormat
Do those line numbers (?) need to be there? If not, it makes copy-pasting this file content confusing because people need to remove those line numbers. I'd leave them out.

2022-09-19 14:17 UTC, tombruijn commented on source/posts/application/logging.mdx
> +2. 501 12734  3242   0  09:00AM ttys000    0:00.01 grep syslog
```suggestion
$ ps -ef |grep syslog
501 12734  3242   0  09:00AM ttys000    0:00.01 grep syslog
```

2022-09-19 14:18 UTC, tombruijn commented on source/posts/application/logging.mdx
> +2. $DebugLevel 1
```suggestion
$DebugFile /somepath/example.log
$DebugLevel 1
```

2022-09-19 14:19 UTC, tombruijn commented on source/posts/application/logging.mdx
> +`` kill -USR1 `cat /var/run/rsyslogd.pid ``
```suggestion
`` kill -USR1 `cat /var/run/rsyslogd.pid` ``
```
I think a backtick is missing here?

It could also use a sub command like so:

```suggestion
`kill -USR1 $(cat /var/run/rsyslogd.pid)`
```

2022-09-19 15:06 UTC, unflxw commented on source/posts/application/logging.mdx
> +Queries can be combined with a space between them (see Combined Queryes in [Search Query Overview](#Search-Query-Overview)).
typo
```suggestion
Queries can be combined with a space between them (see Combined Queries in [Search Query Overview](#Search-Query-Overview)).
```

2022-09-19 15:07 UTC, unflxw commented on source/posts/application/logging.mdx
> +Now we've configured `DebugOnDemmand` we can activate it (and deactivate it) on demand. To do this, in a new terminal window simply execute the following command:
typo
```suggestion
Now we've configured `DebugOnDemand` we can activate it (and deactivate it) on demand. To do this, in a new terminal window simply execute the following command:
```

2022-09-19 15:08 UTC, unflxw commented on source/posts/application/logging.mdx
> +Log Retention will be dependent on what logging plan you have with AppSignal. More information on pricing and retention will be available when Logging is no longer in Beta.
> logging plan

Are there going to be _logging plans_ separate from our regular plans?

2022-09-19 15:08 UTC, unflxw commented on source/posts/application/logging.mdx
> +All information on publically available AppSignal plans, including storage and pricing, can be found on our [Pricing Page](https://www.appsignal.com/plans).
```suggestion
All information on publicly available AppSignal plans, including storage and pricing, can be found on our [Pricing Page](https://www.appsignal.com/plans).
```

2022-09-19 15:10 UTC, unflxw commented on source/posts/application/logging.mdx
> +Before removing a log source, we recommend ensuring that the source is no longer sending logs to AppSignal to ensure your application is not making unnecessary calls to third parties.
_How?_ (this is an example, not sure if rebooting rsyslog is necessary)
```suggestion
Before removing a log source, we recommend ensuring that the source is no longer sending logs to AppSignal so that your application is not making unnecessary calls to third parties. Before removing the log source in AppSignal, remove the rsyslog configuration file for this log source and restart rsyslog.
```

2022-09-19 15:10 UTC, unflxw commented on source/posts/application/logging.mdx
> +Something happen while you were having coffee? No problem. Use the `Jump to date ˬ` button to navigate to the date and time you want to investigate.
```suggestion
Something happened while you were having coffee? No problem. Use the `Jump to date ˬ` button to navigate to the date and time you want to investigate.
```

2022-09-19 15:19 UTC, unflxw commented
Sorry, some overlap between my comments' and everyone else's! I should've refreshed the page. 😅

I haven't worked on this feature, so I'm coming at it for the first time and discovering it alongside the docs. I have to say that the in-app documentation helps a lot.

Some other things that didn't match a specific diff line:

- None of the screenshots show the API keys in the right format. It adds to the confusion about the code snippet and how to put an API key in it. One of the screenshots also says "Rail logs" instead of "Rails logs".
- The app tells you that there will be configuration instructions after you create the source, but it doesn't take you there -- you have to manually click on "Manage source".
- The code snippet probably shouldn't be there at all. It adds to confusion, since it's very hard to figure out where to interpolate the API key, given that the code snippet is itself a template written in an obscure configuration language. It's probably a much better experience for the user to go to "Manage source" and copy the code snippet from there, with the correct API key already interpolated.

2022-09-19 15:20 UTC, unflxw commented on source/posts/application/logging.mdx
> +If you run into issues, you may wish to debug your logs. This section will help guide you through that process for rsyslog using [environment variables](#Environment-Variables) or [command line](#Com
```suggestion
If you run into issues, you may wish to debug your logs. This section will help guide you through that process for rsyslog using [environment variables](#Environment-Variables) or [command line](#Command-Line) to enable [`DebugOnDemand`](https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html#debug-on-demand).
```

2022-09-19 15:22 UTC, unflxw commented on source/posts/application/logging.mdx
> +| `Attribute`  | Attributes defined in your logs (via search)                                   |
The filter fields shouldn't be capitalised here, since they are later shown in the search syntax examples without capitalising, which is how they need to be, I think.

```suggestion
| Filter Field | Description                                                                    |
| ------------ | ------------------------------------------------------------------------------ |
| `source`     | A Log Source from your application, eg MongoDB or Sidekiq                      |
| `severity`   | Log severity level. Accepted values are: error, warning, info, debug and trace |
| `hostname`   | Application Host (via search)                                                  |
| `group`      | Namespaces defined for your application (via search)                           |
| `message`    | Log message contents (via search)                                              |
| `attribute`  | Attributes defined in your logs (via search)                                   |
```

2022-09-19 15:29 UTC, unflxw commented on source/posts/application/logging.mdx
> +7. $template AppsignalFormat,"<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [ls-86f1d33e-df8f-4e74-b39d-3f23971c0983@59115] %msg%\n"
That's part of the API key. It's not clear at all that you need to replace `ls-86f1d33e-df8f-4e74-b39d-3f23971c0983` (but not `@59115` right after that!) with the API key for your logging source. Luckily, the app does give you the already-interpolated snippet.

2022-09-19 15:30 UTC, unflxw commented on source/posts/application/logging.mdx
> +Any changes made (excluding name) will not be applied retrospectively, and therefor will only apply to new logs.
also
```suggestion
Any changes made (excluding name) will not be applied retroactively, and therefor will only apply to new logs.
```

2022-09-20 10:10 UTC, noccor commented on source/posts/application/logging.mdx
> +Queries can be combined with a space between them (see Combined Queryes in [Search Query Overview](#Search-Query-Overview)).
Queryes sounds like a GOT character

2022-09-20 10:12 UTC, noccor commented on source/posts/application/logging.mdx
> +Any changes made (excluding name) will not be applied retrospectively, and therefor will only apply to new logs.
Therefor and Therefore have quite different meanings, [Grammarly can explain](https://www.grammarly.com/blog/therefore-vs-therefor/#:~:text=Therefor,-Marko%20Ticak&text=Therefore%20is%20an%20adverb%20that,%E2%80%9D%20or%20%E2%80%9Cfor%20it.%E2%80%9D)

2022-09-20 10:15 UTC, noccor commented on source/posts/application/logging.mdx
> +To send logs to AppSignal, you'll first need to configure your log sources. You will need to do this once per log source.
Note to self to come back to this.

2022-09-20 10:16 UTC, noccor commented on source/posts/application/logging.mdx
> +Use the `Severity ˬ` drop down to filter the severity of logs
Yeah, I will request a feature for more accurate button rendering, I wanted to see how replicable things where within the current constraints of mdx.

2022-09-20 10:59 UTC, noccor commented on source/posts/application/logging.mdx
> +Log Retention will be dependent on what logging plan you have with AppSignal. More information on pricing and retention will be available when Logging is no longer in Beta.
I believe so, but let's omit any suggestion to that until the Beta is over and the pricing is clear - and just keep the docs linking. Will remove this reference.

2022-09-20 11:36 UTC, noccor commented on source/posts/application/logging.mdx
> +7. $template AppsignalFormat,"<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [ls-86f1d33e-df8f-4e74-b39d-3f23971c0983@59115] %msg%\n"
We can omit this section, it no longer makes sense - earlier there was no installation instruction, and it was unsure how this would be done - but with the current product having this installation section, the docs just need to explain this adequately instead :) thanks!

2022-09-20 12:42 UTC, noccor commented
@tombruijn, @mmaksimovic & @unflxw - thanks for your feedback. I've applied the relevant suggestions and made some changes to the documentation 🥳 

Most notably to the structure of the documentation, which is now in the guides section. 

@tombruijn & @unflxw  - I would like feedback on:

1. The structure
2. If the configuration instructions for rsyslog are now clear enough? (this is the only place with copy changes beyond minor tweaks / your suggestions) 

Jieun has made new screenshots which I will be adding to the PR shortly

2022-09-20 14:37 UTC, thijsc commented on source/posts/guides/logging/log-management.mdx
> +`/etc/rc.d/init.d/rsyslog stop`
Same init.d/systemctl thing here.

2022-09-21 07:36 UTC, roytomeij commented
I'm maybe glancing over it, but I don't see the page on the deploy preview. Where should I be looking for it, @noccor?

2022-09-21 07:41 UTC, roytomeij commented
Ah, it's under "Guides." I think this makes it much too hard to locate, and I'm suggesting moving it to be in the main nav as part of "Features" alongside "Uptime monitoring," etc.

WDYT @thijsc?

2022-09-21 07:53 UTC, roytomeij commented
@noccor, we will use "AppSignal Logging" as the name of this feature. Can you ensure that things like "AppSignal's Logs feature" are named to that?

And another spell check, maybe, because I'm spotting things like "applications logs," which should probably read "application's" :)

2022-09-21 07:55 UTC, roytomeij requested changes

2022-09-21 07:55 UTC, roytomeij commented on source/posts/guides/logging/index.mdx
> +Log Retention will be dependent on what plan you have with AppSignal. More information on pricing and retention will be available when Logging is no longer in Beta.
```suggestion
More information on pricing and retention will be available when Logging is no longer in Beta.
```

Removed the first bit, because that might not be true.

2022-09-21 07:55 UTC, roytomeij commented on source/posts/guides/logging/index.mdx
> +Beta Tester logs are retained for 30 days with a max capacity of 50GB.
```suggestion
Beta Tester logs are retained for 30 days with a maximum capacity of 50GB.
```

2022-09-21 09:02 UTC, tombruijn commented on source/posts/guides/logging/log-management.mdx
> +`ps -ef | grep iterm`
```suggestion
`ps -ef | grep syslog`
```
Should be syslog? That's what the code example below uses.

2022-09-21 09:02 UTC, tombruijn commented on source/posts/guides/logging/log-management.mdx
> +Before removing a log source, we recommend ensuring that the source is no longer sending logs to AppSignal so that your application is not making unnecessary calls to third parties. Before removing t
I would be helpful to mention the configuration file location here so it's easier to complete this step.

2022-09-21 09:02 UTC, tombruijn commented on source/posts/guides/logging/log-management.mdx
> +$ ps -ef |grep syslog
```suggestion
$ ps -ef | grep syslog
```

2022-09-21 09:02 UTC, tombruijn commented
> I would like feedback on:
>     1. The structure

I'd move the entire thing over to the features section like I said before. It doesn't fit well in the guides section. We can still reference it in the guides, but the whole thing itself shouldn't go there. It goes into too much detail for a guide.

>     2. If the configuration instructions for rsyslog are now clear enough? (this is the only place with copy changes beyond minor tweaks / your suggestions)

I left some more comments. But I don't know how rsyslog works to say if it covers everything.

2022-09-21 09:10 UTC, noccor commented on source/posts/guides/logging/log-management.mdx
> +$ ps -ef |grep syslog
This is prettier removing spaces on save - will configure it to not do that.

2022-09-21 09:22 UTC, noccor commented
Okay for now I think we're good for feedback. 

@tombruijn / @roytomeij  - I'm working your suggestions in, thanks! 

@thijsc  - thanks for the sanity check, I'm updating all rsyslog references to reflect that. 

After this there are several minor copy tweaks to be made, and then it should be good to go with @roytomeij's final blessing 🚀 

Thanks everyone!

2022-09-21 09:32 UTC, roytomeij commented
Thanks @noccor! Still some cleaning up to do (URLs still have `/guides/` in them, the copy reference "guides") but otherwise a-okay.

2022-09-21 13:05 UTC, noccor commented on source/posts/guides/logging/log-management.mdx
> +Before removing a log source, we recommend ensuring that the source is no longer sending logs to AppSignal so that your application is not making unnecessary calls to third parties. Before removing t
Great point I also added the restart info too :) !

2022-09-22 09:06 UTC, roytomeij commented on source/posts/logging/index.mdx
> +Beta Tester logs are retained for 30 days with a maximum capacity of 50GB.
Based on new insights:

```suggestion
Beta Tester logs are retained for 30 days with a fair usage storage limit.
```

2022-09-22 16:56 UTC, thijsc approved these changes

2022-09-23 08:58 UTC, roytomeij commented
I can't find it, but maybe I'm overlooking something: what do we have in the docs about PII (Personal Identifiable Information), and the burden on customers to make sure no PII is sent to AppSignal? /cc @noccor @thijsc

2022-09-23 09:24 UTC, thijsc commented
We're probably not covering that yet? We should at least mention that it's the customers own responsibility.

2022-09-23 09:38 UTC, roytomeij commented
Yes. I think we can base this on other references in the docs about PII, and take it from there. @noccor, feel free to discuss this with me over Slack for a more detailed explanation.

2022-09-26 10:18 UTC, roytomeij approved these changes

2022-09-29 06:46 UTC, merged