Nodejs otel docs
appsignal/appsignal-docs pull request #776
Opened 2022-10-06 14:05 UTC by noccor

2022-10-07 07:50 UTC, noccor commented
@roytomeij can you please do a tone of voice check on the following pages, all in Node.js 3.x Documentation. This is where the most copy changes have taken place (partial, or total re-write):

- [ ]  Overview
- [ ]  Migration Guide (note, the Next.js section is not yet complete pending info)
- [ ]  Custom Instrumentation > Overview
- [ ]  Custom Instrumentation > Instrumentation
- [ ]  Custom Instrumentation > Exception Handling

2022-10-12 08:08 UTC, tombruijn commented on source/posts/nodejs/3.x/integrations/express.mdx
> +// at the very top of the entrypoint of your application...
It's not really relevant anymore where you load the middleware. It's important where it's "use"d in the app itself.
```suggestion
```

2022-10-12 08:08 UTC, tombruijn commented on source/posts/nodejs/3.x/integrations/express.mdx
> +const { expressErrorHandler } = require("@appsignal/express");
```suggestion
```
Duplicate import/require can be removed.

2022-10-12 08:08 UTC, tombruijn commented on source/posts/nodejs/3.x/integrations/express.mdx
> +
```suggestion
```
This is now moved to the `appsignal.cjs` file.

2022-10-13 09:17 UTC, roytomeij requested changes
I've left comments and suggestions!

I wonder why we have a paragraph at the bottom of some pages offering help from the Customer Success team but not on all.

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/migration-guide.mdx
> +**Don't forget to [remove/uninstall the AppSignal integration package](#remove-integration-package)**.
There's a styling issue here, probably something for @wesoudshoorn to collaborate on: the link isn't bold while it should be.

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/migration-guide.mdx
> +Once the imports, and code dependent on those imports is removed you need to uninstall the integration package.
```suggestion
Once the imports and code dependent on those imports are removed, you need to uninstall the integration package.
```

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/migration-guide.mdx
> +[Read more about tracers in the 3.x instrumentation documentation](/nodejs/3.x/instrumentation/instrumentation.html)
```suggestion
[Read more about tracers in the 3.x instrumentation documentation.](/nodejs/3.x/instrumentation/instrumentation.html)
```

Suggested because I think a full sentence deserves a period :)

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/migration-guide.mdx
> +[Read more about spans in the 3.x instrumentation documentation](/nodejs/3.x/instrumentation/instrumentation.html)
```suggestion
[Read more about spans in the 3.x instrumentation documentation.](/nodejs/3.x/instrumentation/instrumentation.html)
```

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/migration-guide.mdx
> +[Read more about spans attribute helpers in the 3.x instrumentation documentation](/nodejs/3.x/instrumentation/instrumentation.html)
```suggestion
[Read more about spans attribute helpers in the 3.x instrumentation documentation.](/nodejs/3.x/instrumentation/instrumentation.html)
```

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/migration-guide.mdx
> +[Read more about exception handling in the 3.x exception handling documentation](/nodejs/3.x/instrumentation/exception-handling.html)
```suggestion
[Read more about exception handling in the 3.x exception handling documentation.](/nodejs/3.x/instrumentation/exception-handling.html)
```

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/instrumentation/index.mdx
> +AppSignal provides many ways to provide more insights into your application - by adding more instrumentation or tagging the data that appears in the UI at AppSignal.com. All of the information that w
The dash should be either an en-dash or em-dash (I think em-dash is the best fit here).

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/instrumentation/instrumentation.mdx
> +Our [Example Use Cases](#example-use-case) demonstrate how you can use tracers, spans, and helpers to create your custom instrumentation.
```suggestion
Our [Example Use Cases](#example-use-cases) demonstrate how you can use tracers, spans, and helpers to create your custom instrumentation.
```

(Broken link)

2022-10-13 09:17 UTC, roytomeij commented on source/posts/nodejs/3.x/instrumentation/exception-handling.mdx
> +In most applications some errors will get raised that aren't related to possible bugs in your code, they just happen when your app gets into contact with the real world, like when a bot tries to fill
```suggestion
In most applications, some errors will get raised that aren't related to possible bugs in your code; they just happen when your app gets into contact with the real world, like when a bot tries to fill in a form.
```

2022-10-13 10:38 UTC, luismiramirez commented on source/posts/metrics/custom.mdx
> +// Node.js 2.x
```suggestion
// AppSignal for Node.js 2.x
```

2022-10-13 10:38 UTC, luismiramirez commented on source/posts/metrics/custom.mdx
> +// Node.js 3.x
```suggestion
// AppSignal for Node.js 3.x
```

2022-10-13 10:38 UTC, luismiramirez commented on source/posts/nodejs/3.x/integrations/nextjs.mdx
> +Next.js is instrumented automatically by the AppSignal for Node.js package. You do not need to install any additional packages to use Next.js.
The request handler is no longer required. All references to it and to the `@appsignal/nextjs` need to be removed from the samples in this file.

2022-10-13 10:52 UTC, luismiramirez commented on source/posts/nodejs/3.x/integrations/nextjs.mdx
> +In Next.js 9.4.0, support was added for [Core Web Vitals](https://web.dev/vitals/) reporting. Core Web Vitals are the quality signals key to delivering great UX on the web, on top of which the famous
We can remove this line entirely

2022-10-13 13:03 UTC, noccor commented on source/posts/nodejs/3.x/migration-guide.mdx
> +**Don't forget to [remove/uninstall the AppSignal integration package](#remove-integration-package)**.
note to self: make screenshot and create ticket

2022-10-14 10:03 UTC, merged