Add NDJSON HTTP
appsignal/appsignal-docs pull request #781
Opened 2022-10-12 09:13 UTC by noccor

2022-10-12 13:10 UTC, matsimitsu approved these changes

2022-10-13 11:07 UTC, roytomeij requested changes
In addition to my line comments, I think we could also use the [Redirector](https://github.com/appsignal/handbook/blob/main/support/redirector.md) to include links to some relevant parts of the application.

2022-10-13 11:07 UTC, roytomeij commented on source/posts/logging/platforms/http.mdx
> +  - int Integer numbers (10)
```suggestion
  - int Integer numbers (`10`)
```

2022-10-13 11:07 UTC, roytomeij commented on source/posts/logging/platforms/http.mdx
> +  - double Double/Floats (0.01)
```suggestion
  - double Double/Floats (`0.01`)
```

2022-10-13 11:07 UTC, roytomeij commented on source/posts/logging/platforms/http.mdx
> +You can `POST` logs to AppSignal in several formats, more detailed information about each format can be found in the [Log Formatting documentation](/logging/formatting.html), via the links below.
```suggestion
You can `POST` logs to AppSignal in several formats. More detailed information about each format can be found in the [Log Formatting documentation](/logging/formatting.html), via the links below.
```

2022-10-13 11:07 UTC, roytomeij commented on source/posts/logging/platforms/http.mdx
> +  format, fields or incorrect values.
```suggestion
  format, fields, or incorrect values.
```

2022-10-14 07:29 UTC, roytomeij approved these changes

2022-10-14 07:30 UTC, roytomeij commented
From a tone of voice, etc point of view I think this is good to merge. Might need @matsimitsu for a technical check.

2022-10-14 07:32 UTC, roytomeij commented on source/posts/logging/configuration.mdx
> +- [Heroku Logdrian](platforms/heroku.html)
```suggestion
- [Heroku Logdrain](platforms/heroku.html)
```

2022-10-14 07:33 UTC, matsimitsu commented
There are a few inconsistencies, but we have a call in an hour to run through those :)

2022-10-17 10:42 UTC, roytomeij commented
Is this ready to be merged, @noccor?

2022-10-17 12:04 UTC, merged