Docs for logging from Ruby
appsignal/appsignal-docs pull request #820
Opened 2022-11-01 11:51 UTC by thijsc

Basic docs for the first customers that will try logging from the Ruby integration.

2022-11-02 11:34 UTC, thijsc commented
Nice 👍

2022-11-02 11:44 UTC, noccor commented
@roytomeij - tone of voice check?

2022-11-04 13:44 UTC, roytomeij requested changes

2022-11-04 13:44 UTC, roytomeij commented on source/posts/logging/platforms/integrations/index.mdx
> +Currently, logging is only available for our Ruby integration, logging will be expanded to support other integrations soon.
```suggestion
Currently, logging is only available for our Ruby integration. Logging will be expanded to support other integrations soon.
```

2022-11-04 13:44 UTC, roytomeij commented on source/posts/logging/platforms/integrations/index.mdx
> +- [Ruby](ruby.html)
This link returns a `404` in the preview.

2022-11-04 13:44 UTC, roytomeij commented on source/posts/logging/configuration.mdx
> +  Integration](platforms/integrations).
```suggestion
  Integrations](platforms/integrations).
```

2022-11-04 13:44 UTC, roytomeij commented on source/posts/logging/configuration.mdx
> +in this instance you don't need to create a source and should instead following seperate installation instructions for your integration. More information can be found in the [Logging From AppSignal I
```suggestion
In this instance, you don't need to create a source and should follow separate installation instructions for your integration. More information can be found in the [Logging From AppSignal Integration documentation](platforms/integrations).
```

2022-11-04 13:44 UTC, roytomeij commented on source/posts/logging/platforms/integrations/ruby.mdx
> +You can query and filter on message contents, and attribute values from within the [Log Management](/logging/log-management.html) tool.
```suggestion
You can query and filter on message contents and attribute values from within the [Log Management](/logging/log-management.html) tool.
```

2022-11-04 14:37 UTC, noccor commented
@roytomeij - feedback taken onboard, with some other minor adjustments + docs wide dead link check

2022-11-04 14:39 UTC, noccor commented on source/posts/logging/configuration.mdx
> +  Integrations](platforms/integrations) documentation.
Where my choice of capitalization bites, here it's AppSignal Integrations, referring to the page title.

2022-11-08 08:53 UTC, thijsc commented
We are running a migration and will be ready to ship end of the day or tomorrow morning. Can we get the last details for this wrapped up?

2022-11-08 11:52 UTC, roytomeij approved these changes

2022-11-09 10:12 UTC, roytomeij commented
Has the feature been shipped, so we can ship the docs as well?

2022-11-09 10:30 UTC, merged