Logging elixir node
appsignal/appsignal-docs pull request #859
Opened 2022-11-14 15:04 UTC by luismiramirez

[Add Elixir logging page](https://github.com/appsignal/appsignal-docs/commit/0feef500b592dca7d5bf6aad7be38d4d05c0b4cf)

Page that contains info about the usage of the first version of the
logging feature for the Elixir integration.

[Add Node.js logging page](https://github.com/appsignal/appsignal-docs/commit/c031ec5de455928cff163ed1e866ef3900be0dc1)

Page that contains info about the usage of the first version of the
logging feature for the Node.js integration.

2022-11-15 08:22 UTC, tombruijn requested changes

2022-11-15 08:22 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +To use logging with your AppSignal integration for Node.js, you first need to install the `implement-logging-feature` branch of the AppSignal package. To do this, open your application's `Package.jso
```suggestion
To use logging with your AppSignal integration for Node.js, you first need to install the `implement-logging-feature` branch of the AppSignal package. To do this, open your application's `package.json`, and find the `@appsignal/nodejs` package:
```

2022-11-15 08:22 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +    "appsignal": "^3.0.0" // Don't mind the version as long as you use > 3.0
```suggestion
    "@appsignal/nodejs": "^3.0.0" // Don't mind the version as long as you use > 3.0
```

2022-11-15 08:22 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +    "appsignal": "github:appsignal/appsignal-nodejs#implement-logging-feature"
```suggestion
    "@appsignal/nodejs": "github:appsignal/appsignal-nodejs#implement-logging-feature"
```

2022-11-15 08:22 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +logger.info("User logged in", { user_id: 123 });
```suggestion
// In other places of your app
const { logger } = require("./appsignal.cjs");

logger.info("Log message line");
logger.info("User logged in", { user_id: 123 });
```

If users need to access the client we either need to export it or mention a way to access the global accessor.

2022-11-15 08:22 UTC, tombruijn commented on source/posts/logging/platforms/integrations/elixir.mdx
> +Appsignal.debug("app", "Something went wrong with customer: #{customer_id}", %{customer_id: 123, post_id: 234})
```suggestion
Appsignal.debug("app", "Log message line")
Appsignal.debug("app", "Something went wrong with customer: #{customer_id}", %{customer_id: 123, post_id: 234})
```

2022-11-15 08:22 UTC, tombruijn commented on source/posts/logging/platforms/integrations/elixir.mdx
> +Appsignal.debug("app", "Something went wrong with customer: #{customer_id}", %{customer_id: 123, post_id: 234})
Is it necessary to also include the customer_id in the message if it's also part of the attributes? The Node.js example doesn't do this.

2022-11-15 08:22 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = client.logger("app", "debug");
```suggestion
module.exports = { appsignal: client };
```
Part of comment below.

2022-11-15 09:35 UTC, luismiramirez commented on source/posts/logging/platforms/integrations/elixir.mdx
> +Appsignal.debug("app", "Something went wrong with customer: #{customer_id}", %{customer_id: 123, post_id: 234})
It's not necessary, it's just an example.

2022-11-15 16:21 UTC, unflxw approved these changes

2022-11-15 16:21 UTC, unflxw commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = client.logger("app", "debug");
Let's avoid asking users to export the client, and instead ask them to use `Appsignal.client` (or for this use case, `Appsignal.logger`) from the global object, as is done in other parts of the 3.0 documentation:

```js
# app.js -- NOT appsignal.cjs
import { Appsignal } from "@appsignal/nodejs";

logger = Appsignal.logger("groupname")
logger.debug("blajah")

2022-11-16 07:19 UTC, thijsc approved these changes

2022-11-16 07:34 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = client.logger("app", "debug");
That also looks okay with me. That way we don't have to ask users to export and require it later. But we do need to change it to create the logger in the file where's it's used.

2022-11-16 08:56 UTC, luismiramirez commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = client.logger("app", "debug");
True, let's promote the usage of the globally stored client.

2022-11-16 11:07 UTC, luismiramirez commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = client.logger("app", "debug");
I rephrased stuff a bit with your suggestions here: https://github.com/appsignal/appsignal-docs/pull/859/commits/674ab78b360c5ff8851de870b213894fbebfd8d2

2022-11-16 12:07 UTC, unflxw commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const { Appsignal } = from "@appsignal/nodejs";
I'm guessing you meant one of:

```suggestion
import { Appsignal } from "@appsignal/nodejs";
```

```suggestion
const { Appsignal } = require("@appsignal/nodejs");
```

2022-11-16 12:08 UTC, unflxw commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = client.logger("app", "debug");
Looks good to me (modulo the other comment)

2022-11-17 10:16 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = Appsignal.logger("app");
```suggestion
```

We wanted to move this to the example below, right?

2022-11-17 10:16 UTC, tombruijn commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +```js
```suggestion
```js
const { Appsignal } = require("@appsignal/nodejs");

logger = Appsignal.logger("groupname")
```

Part of the comment above this one.

2022-11-17 10:52 UTC, luismiramirez commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = Appsignal.logger("app");
My idea was to split the code example in two, so it fits with the explanations from each paragraph. That's why it's like that.

2022-11-17 10:55 UTC, luismiramirez commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +const logger = Appsignal.logger("app");
This first block says: 

```
To get the logger you need to import AppSignal after initializing the client and set it up with the `.logger()` function.
```

and the `// In other places of your app` comment clarifies it. We've done the same in other parts of our docs.

2022-11-17 11:27 UTC, noccor requested changes
Minor copy changes suggested - but otherwise looks good!

2022-11-17 11:27 UTC, noccor commented on source/posts/logging/platforms/integrations/elixir.mdx
> +There's a new module exposed in the integration: `Appsignal.Logger`. It provides eight functions:
```suggestion
Once the logging branch has been successfully installed, your Elixir integration will include a new `Appsignal.Logger` module, which provides eight functions. 

Each of these functions correspond to the severity of the log message:
```

2022-11-17 11:27 UTC, noccor commented on source/posts/logging/platforms/integrations/elixir.mdx
> +The first two arguments are the `group` and the `message`. The third is an optional one for `metadata`.
```suggestion
These functions accept three arguments in the following order: `group`, `message`, and optionally `metadata`. The examples below show how you can use these arguments in your application when creating new logs:
```

2022-11-17 11:27 UTC, noccor commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +To get the logger you need to import AppSignal after initializing the client and set it up with the `.logger()` function. It accepts two arguments: `group` and `severityThreshold`. `severityThreshold
```suggestion
To use the logger, you need to import AppSignal after initializing the client and set it up with the `.logger()` function. 

The `.logger()` function accepts two arguments: `group` and optionally `severityThreshold`. If `severityThreshold` is not provided, it will default to `info`.
```

2022-11-17 11:27 UTC, noccor commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +Note that if the severity of the message is above the severity threshold set up when initializing the logger, it'll never get to AppSignal.
```suggestion
Note that if the message's severity is above the severity threshold set up when initializing the logger, it will not be sent to AppSignal. 
```

2022-11-17 15:34 UTC, noccor approved these changes

2022-11-21 11:44 UTC, luismiramirez commented
Merge on hold until Node.js is released: https://github.com/appsignal/appsignal-nodejs/issues/793

2022-11-22 12:04 UTC, unflxw commented on source/posts/logging/platforms/integrations/elixir.mdx
> +{:appsignal, git: "https://github.com/appsignal/appsignal-elixir", branch: "logging-feature"}
Since we have released new versions with the logging feature, let's remove the references to specific branches.

2022-11-22 12:05 UTC, unflxw commented on source/posts/logging/platforms/integrations/nodejs.mdx
> +There are five severity levels available `trace`, `debug`, `info`, `warn`, and `error` each of them with its own function with the same name. These functions accept two arguments `message` and `attri
```suggestion
There are six severity levels available `trace`, `debug`, `info`, `log`, `warn`, and `error` each of them with its own function with the same name. These functions accept two arguments `message` and `attributes`. Attributes is used for metadata and is optional.
```

2022-11-23 09:15 UTC, tombruijn approved these changes

2022-11-24 08:26 UTC, jeffkreeftmeijer approved these changes

2022-11-24 08:47 UTC, merged

2022-11-28 13:11 UTC, unflxw commented on source/posts/logging/platforms/integrations/elixir.mdx
> +Appsignal.debug("app", "Something went wrong with customer: #{customer_id}", %{customer_id: 123, post_id: 234})
Hm, shouldn't this be `Appsignal.Logger.debug()`?

2022-11-29 08:03 UTC, luismiramirez commented on source/posts/logging/platforms/integrations/elixir.mdx
> +Appsignal.debug("app", "Something went wrong with customer: #{customer_id}", %{customer_id: 123, post_id: 234})
Yes! Thanks for fixing it.